apiVersion: apps/v1
kind: Deployment
metadata:
  name: httplog-exporter
  labels:
    app.kubernetes.io/name: httplog-exporter
    app.kubernetes.io/component: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: httplog-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: httplog-exporter
        app.kubernetes.io/component: exporter
    spec:
      serviceAccountName: httplog-exporter
      containers:
      - name: httplog-exporter
        image: httplog-exporter:latest
        ports:
        - containerPort: 8080
          name: http-metrics
          protocol: TCP
        env:
        - name: TARGET_NAMESPACE
          value: "appstudio-workload-monitoring"
        - name: SCRAPE_INTERVAL_SECONDS
          value: "30"
        - name: LOG_LINES_LIMIT
          value: "200"
        - name: POD_SELECTOR
          value: "app.kubernetes.io/part-of=konflux"
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httplog-exporter
  labels:
    app.kubernetes.io/name: httplog-exporter
    app.kubernetes.io/component: exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httplog-exporter
  labels:
    app.kubernetes.io/name: httplog-exporter
    app.kubernetes.io/component: exporter
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: httplog-exporter
  labels:
    app.kubernetes.io/name: httplog-exporter
    app.kubernetes.io/component: exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: httplog-exporter
subjects:
- kind: ServiceAccount
  name: httplog-exporter
  namespace: appstudio-workload-monitoring 